config/routes.rb
Rails.application.routes.draw do

  get 'simple_pages/landing_page'
  resources :products
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'products#index'
  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.includes(:product).all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @products, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end

  def landing_page
    @products = Product.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes Berlin</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway%7CMerriweather%7CCousine">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body data-target=".navbar">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
  data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="projectName">
            <%= link_to "Bikes Berlin", root_path, class: "navbar-brand" %>
          </div> <!--end projectName -->
        </div><!-- end navbar header-->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(simple_pages_about_path) %>"><%= link_to "About", simple_pages_about_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(simple_pages_contact_path) %>"><%= link_to "Contact", simple_pages_contact_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Orders", orders_path, class: "dropdown-toggle" %></li>            <!-- Navbar link with a dropdown menu -->
            <!--  <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  Products<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path, class: "dropdown-toggle" %></li>
                    <li class="<%= 'active' if current_page?(new_product_path) %>"><%= link_to "New Products", new_product_path, class: "dropdown-toggle" %></li>

                  </ul>
              </li>
              <!--
            <li><a href="#faq" class="dropdown-toggle">FAQ</a></li>
            <li><a href="#video" class="dropdown-toggle">Video</a></li>
          -->
          </ul>
        </div><!-- end navbar collapse -->
      </div><!-- end nav container-->
    </nav><!-- end navbar -->

    <%= yield %>

    <footer>
     <div class="try">
      <div class="copyright">
        <div class="text">&copy; Bike Berlin 2018
        </div>
      </div>
      <div class="resume">

        <div class="beside"><a href="http://www.bikeawayberlin.com" target="_blank">Bike A-Way</a></div>
        <div class="beside"><a href="http://www.berliner-fahrradlaeden.de/A-und-V-Second-Bike/" target="_blank">Second Bike</a></div>
        <div class="beside"><a href="https://twitter.com/bohdanlaluck1?ref_src=twsrc%5Etfw" class="twitter-follow-button"  data-show-screen-name="false" data-lang="en" data-show-count="false">Follow @bohdanlaluck1</a><script async src="https://platform.twitter.com/widgets.js" ></script></div>
        <div class="fb-like beside" data-href="http://laughing-thompson-954b7b.bitballoon.com/" data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>

      </div>
    </div>

  </body>
</html>

app/views/orders/index.html.erb
<div class="container-fluid section-start" id="orders-index">
  <h1>Orders</h1>
  <div class="row">
    <% @orders.each do |order| %>
      <div class="col-sm">
        <h1>
          Order # <%= order.id %>:
          <%= link_to order.product.name, order %>
        </h1>
        <p><%= order.product.description %></p>
        <strong>$ <%= order.product.price %></strong>
      </div><!-- /col -->
    <% end %>
    </div>
  
</div>

app/views/orders/show.html.erb
<div class="container-fluid section-start" id="orders-show">
  <h2>Order Information</h2>
  <strong>Order ID: </strong><%= @order.id %>
  <strong>Product Name: </strong><%= @order.product.name %>
  <strong>Product Price: </strong><%= number_to_currency(@order.product.price) %>
  <strong>Total Price: </strong><%= number_to_currency(@order.total) %>
  <br>
  <br>
  <%= link_to 'Go To All Orders', orders_path, class: "btn btn-warning" %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/products/_product.html.erb
  <div class="col-xs-12  col-sm-6 col-md-4 col-lg-3  ">
    <%= image_tag(product.image_url, class: "img-fluid img-responsive img-modify") %>
      <h1><%= product.name %></h1></a>
      <p><%= product.description %></p><hr>
      <h2>$ <%= product.price %></h2>

      <%= link_to 'Show', product %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>

app/views/products/edit.html.erb
<div class="container-fluid section-start" id="edit-product">

  <h1>Editing Product: <%= @product.name %></h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Show', @product, class: "btn btn-success bottom-link" %>
  <%= link_to 'Back', request.referer, class: "btn btn-warning bottom-link" %>
</div>

app/views/products/index.html.erb
<div class="container-fluid section-start" id="index-product">
  <p id="notice"><%= notice %></p>

  <h1>Products</h1>


    <div class="row">

        <%= render @products %>

   </div>



  <br>

  <%= link_to 'New Product', new_product_path, class: "btn btn-warning" %>
</div>

app/views/products/new.html.erb
<div class="container-fluid section-start" id="new-product">
  <h1>New Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Back', request.referer, class: "btn btn-warning bottom-link" %>
</div>

app/views/products/show.html.erb
<div class="container-fluid section-start" id="show-product">
  <p id="notice"><%= notice %></p>

  <h1>Showing Product: <%= @product.name %> </h1>
  <p>
    <h2>Name:</h2>
    <%= @product.name %>
  </p>

  <p>
    <h2>Description:</h2>
    <%= @product.description %>
  </p>

  <p >
    <h2>Image url:</h2>
    <%= @product.image_url %>
  </p>

  <p >
    <h2>Cost:</h2>
    <%= @product.price %>
  </p>

  <p class="last-section-p">
    <h2>Colour</h2>
    <%= @product.colour %>
  </p>


  <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-info bottom-link" %>
  <%= link_to 'Back', request.referer, class: "btn btn-warning bottom-link" %>
</div>

app/views/simple_pages/about.html.erb
<div class="container-fluid section-start" id="about">
  <h1>About</h1>
  <h2>Finding used bikes for Berliners for over 40 years.</h2>
</div>

app/views/simple_pages/contact.html.erb
<div class="container-fluid section-start" id="contact">
  <h1>Contact</h1>
  <h2>We are always happy to help in any way we can.</h2>
  <p>You can reach us at: 1-800-WE-HEAR-U (1-800-934-3278)</p>
</div>

app/views/simple_pages/index.html.erb
<div class="container-fluid section-start" id="index">
  <h1>Welcome to Bike Berlin</h1>
  <h2>Your source for used bikes in Berlin.</h2>
  <div>
  <%= image_tag("racebike2.jpg", class: "img-responsive my-image img") %>
  </div>
</div>

app/views/simple_pages/landing_page.html.erb
<div class="container-fluid section-start" id="index">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @products.each_with_index do |product, index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%=index%>" class="<%= ' active' if product == @products.first%>"></li>
      <% end %>

    </ol>
    <div class="carousel-inner">

            <% @products.each do |product| %>
            <div class="carousel-item item<%= ' active' if product == @products.first %>">
              <%= image_tag(product.image_url, class: "img-fluid img-responsive image-carousel") %>

              <div class="carousel-caption d-none d-md-block">
                <p><%= product.name %></p>
              </div>
            </div>
            <% end %>

       </div>
    <a class="left carousel-control" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>